backend: sklearn
model:
  name: src.models.gcn.GCN
  hidden_size: 16
  dropout: 0.5
dataset:
  name: src.datasets.cora.Cora
train:
  num_epochs: 200
  batch_size: 2708
  eval: [valid, test]
  optimizer:
    name: adam
    lr: 0.01
    weight_decay: 5e-4
test:
  metrics: [acc]