backend: sklearn
model:
  name: src.models.gcn.GCN

  dimensions: 128
  walk_length: 80
  num_walks: 10
  window_size: 10
  directed: false
  p: 0.25
  q: 0.25

  hidden_size: 64
  dropout: 0.5
dataset:
  name: src.datasets.blog_catalog.BlogCatalog
train:
  num_epochs: 200
  batch_size: 512
  eval: [test]
  optimizer:
    name: adam
    lr: 0.1
    weight_decay: 5e-4
test:
  metrics: [acc]