backend: pytorch
random_seed: 42
env:
  default:
    variables:
      batch_size: 256
      hidden_dim: 64
      num_encoder_layers: 4
      num_decoder_layers: 4
      dropout: 0.0
      learning_rate: 0.01
      num_epochs: 500
      batch_norm: true
  mutag:
    variables:
      dataset:
        - MUTAG
      feature_name:
        - muldim
      hidden_dim: 32
      signature: [rpf]
      learning_rate: 0.05
      batch_size: 32
      num_epochs: 150
  reddit:
    default: false
    variables:
      dataset:
        - REDDIT-BINARY
        #- REDDIT-MULTI-5K
        #- REDDIT-MULTI-12K
      feature_name:
        #- multi_1.2.3.4.5.6.7.8
        - freq_multi_1.3.5.7
        #- embed_rpf_2.4.6.8
        #- embed_rpf_4.8.12.16
        #- embed_rpf_2.4.6
        #- embed_rpf_3.6.9
      hidden_dim: [64, 128]
      signature: [rpf]
      # learning_rate: 0.05
      batch_size: 128
      num_epochs: 200
  reddit5k:
    default: false
    variables:
      dataset:
        - REDDIT-MULTI-5K
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      hidden_dim: [64, 128]
      signature: [rpf]
      learning_rate: 0.05
      batch_size: 32
      num_epochs: 250
  reddit12k:
    default: false
    variables:
      dataset:
        - REDDIT-MULTI-12K
      feature_name:
        - freq_multi_1.2.3.4.5.6.7.8
        - freq_multi_1.3.5.7
      hidden_dim: 128
      signature: [rpf]
      learning_rate: 0.1
      num_epochs: 250
      batch_size: 32
  imdb:
    default: false
    variables:
      dataset:
        #- IMDB-BINARY
        - IMDB-MULTI
      feature_name:
        #- multi_0_1
        #- multi_0_1.2.3.4.5.6.7.8
        - freq_multi_1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16
        #- freq_multi_1.3.5.7
        #- freq_multi_1.3.5.7.9.11.13.15
        #- embed_rpf_1.3.5.7
        #- embed_rpf_2.4.6.8
        #- embed_rpf_1.2.3.4.5.6.7.8
      hidden_dim: 64
      signature: [rpf, ns]
      num_epochs: 200
      batch_size: 256
      learning_rate: 0.1
  collab:
    default: false
    variables:
      dataset:
        - COLLAB
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      hidden_dim: [32, 64]
      signature: rpf
  cox2_dhfr:
    default: false
    variables:
      dataset: [COX2, DHFR]
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      signature: [rpf, rpf_lbl]
      hidden_dim: 32
      num_epochs: 500
      batch_size: 768
  frank:
    default: false
    variables:
      dataset:
        - FRANKENSTEIN
      feature_name:
        - embed_rpf_1
        - embed_rpf_2.4.6.8
        - embed_rpf_1.3.5.7
        - embed_rpf_1.2.3.4.5.6.7.8
      hidden_dim: 32
      dense_dim: 32
      signature: [rpf]
    report:
      type: raw
      reduce: []
  synthetic:
    default: false
    variables:
      dataset:
        - SYNTHETIC
      feature_name:
        - embed_rpf_1
        - embed_rpf_2.4.6.8
        - embed_rpf_1.3.5.7
        - embed_rpf_1.2.3.4.5.6.7.8
      hidden_dim: 64
      dense_dim: 64
      signature: [rpf, rpf_lbl]
    report:
      type: raw
      reduce: []
model:
  name: src.models.set_transformer.MultiDeepSets
  hidden_dim: ~hidden_dim
  num_encoder_layers: ~num_encoder_layers
  num_decoder_layers: ~num_decoder_layers
  dense_dim: ~hidden_dim
  dropout: ~dropout
  batch_norm: true
dataset:
  name: src.datasets.grakel.Grakel
  dataset_name: ~dataset
  graph_kernel: bottleneck_distance
  graph_features:
    persistence_diagram:
      type: persistence_diagram
      key: ~feature_name
      filtration: vertex_weight_norm
      signature: ~signature
  reuse: true
  test_size: 0.1
  batch_norm: ~batch_norm
train:
  num_epochs: ~num_epochs
  early_stop:
    num_epochs: 50
  batch_size: ~batch_size
  optimizer:
    name: adam
    lr: ~learning_rate
  lr_scheduler:
    # milestones: [15, 30, 45, 60]
    milestones: [25, 50, 75, 100, 125, 150]
    gamma: 0.5
  cross_validation: 10
  save_every: 1000e
test:
  metrics: [acc]