backend: pytorch
random_seed: 0
env:
  default:
    variables:
      batch_size: 256
      hidden_dim: 64
      dropout: 0.0
      learning_rate: 0.01
      early_stop: 50
      num_encoder_layers: 4
      num_decoder_layers: 4
      num_epochs: 500
      batch_norm: false
  mutag:
    default: false
    variables:
      dataset: MUTAG
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      signature: [rpf]
      hidden_dim: 32
      num_epochs: 200
  nci:
    default: false
    variables:
      dataset:
        - NCI1
        - NCI109
      feature_name:
        - freq_multi_1
        - freq_multi_1.2.3.4.5.6.7.8
        - freq_multi_1.3.5.7.9.11.13.15
      si:qgnature: [rpf, ns]
      batch_norm: false
      num_epochs: 200
  dd:
    default: false
    variables:
      dataset: DD
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      hidden_dim: [32, 64]
      signature: [rpf, rpf_lbl]
      num_epochs: 200
  proteins:
    default: false
    variables:
      dataset: PROTEINS
      feature_name:
        - multi_1.3.5.7.9.11.13.15
        - multi_1.2.3.4.5.6.7.8
        - multi_1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16
      signature: [rpf, ns]
      hidden_dim: 32
      num_epochs: 200
      batch_size: 1024
      batch_norm: false
      num_encoder_layers: 2
      num_decoder_layers: 2
  enzymes:
    default: false
    variables:
      dataset: [ENZYMES]
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      hidden_dim: [32, 64]
      batch_size: 768
      signature: [rpf, rpf_lbl]
      num_epochs: 200
  ptc:
    default: false
    variables:
      dataset:
        - PTC_MR
        - PTC_FR
        - PTC_MM
        - PTC_FM
      feature_name:
        #- multi_1
        - multi_1.2.3.4.5.6.7.8
      hidden_dim: [32, 64]
      batch_size: 512
      dropout: [0.0, 0.5]
      batch_norm: true
      signature: [rpf, rpf_label]
      learning_rate: 0.01
      num_encoder_layers: 2
      num_decoder_layers: 2
  reddit:
    default: false
    variables:
      dataset:
        - REDDIT-BINARY
      feature_name:
        - freq_multi_1.2.3.4.5.6.7.8
        #- embed_rpf_1.3.5.7
        #- embed_rpf_2.4.6.8
        #- embed_rpf_4.8.12.16
        #- embed_rpf_2.4.6
        #- embed_rpf_3.6.9
      hidden_dim: 64
      signature: [rpf, ns]
      num_epochs: 200
      batch_norm: false
      batch_size: 256
  reddit5k:
    default: false
    variables:
      dataset:
        - REDDIT-MULTI-5K
      feature_name:
        - freq_multi_1.2.3.4
        - freq_multi_1.2.3.4.5.6.7.8
      hidden_dim: 64
      dropout: 0.0
      signature: ns
      learning_rate: 0.01
      batch_size: 128
      num_epochs: 200
  reddit12k:
    default: false
    variables:
      dataset:
        - REDDIT-MULTI-12K
      feature_name:
        - freq_multi_1.2.3.4
        - freq_multi_1.2.3.4.5.6.7.8
      hidden_dim: [64]
      signature: [rpf]
      batch_size: 128
      learning_rate: 0.01
      num_epochs: 200
  imdb:
    default: false
    variables:
      dataset:
        - IMDB-BINARY
        - IMDB-MULTI
      feature_name:
        - multi_1.2.3.4
      hidden_dim: 64
      batch_size: 1024
      signature: [rpf, ns]
  collab:
    default: false
    variables:
      dataset:
        - COLLAB
      feature_name:
        #- multi_1.2.3.4.5.6.7.8
        - multi_1.3.5.7.9.11.13.15
      hidden_dim: 128
      dropout: 0.0
      signature: rpf
      num_epochs: 200
      num_encoder_layers: 4
      num_decoder_layers: 4
      batch_size: 1024
  cox2_dhfr:
    default: false
    variables:
      dataset: [COX2, DHFR]
      feature_name:
        - multi_1.2.3.4.5.6.7.8
      signature: [rpf, rpf_lbl]
      hidden_dim: 32
      num_epochs: 500
      batch_size: 728
      batch_norm: true
      num_encoder_layers: 2
      num_decoder_layers: 2
      # dropout: 0.2
  frank:
    default: false
    variables:
      dataset:
        - FRANKENSTEIN
      feature_name:
        - embed_rpf_1
        - embed_rpf_2.4.6.8
        - embed_rpf_1.3.5.7
        - embed_rpf_1.2.3.4.5.6.7.8
      hidden_dim: 32
      dense_dim: 32
      signature: [rpf]
    report:
      type: raw
      reduce: []
  synthetic:
    default: false
    variables:
      dataset:
        - SYNTHETIC
      feature_name:
        - embed_rpf_1
        - embed_rpf_2.4.6.8
        - embed_rpf_1.3.5.7
        - embed_rpf_1.2.3.4.5.6.7.8
      hidden_dim: 64
      dense_dim: 64
      signature: [rpf, rpf_lbl]
model:
  name: src.models.set_transformer.MultiWeightedDeepSets
  hidden_dim: ~hidden_dim
  num_encoder_layers: ~num_encoder_layers
  num_decoder_layers: ~num_decoder_layers
  dense_dim: ~hidden_dim
  dropout: ~dropout
  batch_norm: ~batch_norm
  multi_encoder: true
dataset:
  name: src.datasets.grakel.Grakel
  dataset_name: ~dataset
  graph_features:
    persistence_diagram:
      type: persistence_diagram
      key: ~feature_name
      filtration: vertex_weight
      signature: ~signature
      max_length: 10000
      quantized_size: 100
  reuse: true
  test_size: 0.1
train:
  num_epochs: ~num_epochs
  early_stop:
    num_epochs: 50
  batch_size: ~batch_size
  optimizer:
    name: adam
    lr: ~learning_rate
  lr_scheduler:
    # milestones: [15, 30, 45, 60]
    milestones: [25, 50, 75, 100, 125, 150]
    gamma: 0.5
  cross_validation: 10
  save_every: 1000e
test:
  metrics: [acc]