backend: pytorch
model:
  name: dlex.torch.models.DNN
  layers: [100, 50, 20]
dataset:
  name: src.datasets.grakel.Grakel
  dataset_name: REDDIT-MULTI-5K
  graph_vector: persistence_landscape
  graph_filtration: vertex_degree
  test_size: 0.1
train:
  num_epochs: 100
  batch_size: 128
  optimizer:
    name: sgd
    lr: 0.1
  lr_scheduler:
    milestones: [20, 40, 60]
    gamma: 0.1
test:
  metrics: [acc]