backend: pytorch
model:
  name: src.models.vertex_weight_persistent_feature.Model
  kernel: precomputed
dataset:
  name: src.datasets.grakel.Grakel
  dataset_name: REDDIT-MULTI-12K
  graph_kernel: bottleneck_distance
  graph_filtration: vertex_degree
  test_size: 0.1
train:
  num_epochs: 40
  batch_size: 128
  optimizer:
    name: sgd
    lr: 0.1
  lr_scheduler:
    milestones: [10, 20, 30]
    gamma: 0.1
test:
  metrics: [acc]